//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanDoAn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_SanPhamEntities : DbContext
    {
        public QL_SanPhamEntities()
            : base("name=QL_SanPhamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblChiTietHoaDon> tblChiTietHoaDon { get; set; }
        public virtual DbSet<tblDanhMucCon> tblDanhMucCon { get; set; }
        public virtual DbSet<tblHinhAnh> tblHinhAnh { get; set; }
        public virtual DbSet<tblHoaDon> tblHoaDon { get; set; }
        public virtual DbSet<tblKhachHang> tblKhachHang { get; set; }
        public virtual DbSet<tblLoaiSP> tblLoaiSP { get; set; }
        public virtual DbSet<tblNhanVien> tblNhanVien { get; set; }
        public virtual DbSet<tblSanPham> tblSanPham { get; set; }
        public virtual DbSet<tbltaikhoan> tbltaikhoan { get; set; }
        public virtual DbSet<tblTinhTrang> tblTinhTrang { get; set; }
        public virtual DbSet<tblVaiTro> tblVaiTro { get; set; }
    }
}
