//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDanhMucCon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDanhMucCon()
        {
            this.tblSanPham = new HashSet<tblSanPham>();
        }
    
        public int MaDM { get; set; }
        public string TenDM { get; set; }
        public Nullable<int> MaLoai { get; set; }

        [Newtonsoft.Json.JsonIgnore]
        public virtual tblLoaiSP tblLoaiSP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        [Newtonsoft.Json.JsonIgnore]
        public virtual ICollection<tblSanPham> tblSanPham { get; set; }
    }
}
