//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltaikhoan
    {
        public string username { get; set; }
        public string matkhau { get; set; }
        public Nullable<int> manv { get; set; }
        public Nullable<int> makh { get; set; }
        public Nullable<int> mavaitro { get; set; }
    
        public virtual tblKhachHang tblKhachHang { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
        public virtual tblVaiTro tblVaiTro { get; set; }
    }
}
